### ISSUE TITLE
What is cufiNUFFT using streams for at the moment

### ISSUE THREAD

**Issue by JBlaschke** [flatironinstitute/cufinufft#117]
While researching https://github.com/dfm/jax-finufft/pull/4#issuecomment-974480880 I came across:
https://github.com/flatironinstitute/cufinufft/blob/a8c979e6e70a5303a4384b01a71c86c973a79696/src/memtransfer_wrapper.cu#L88,
and was wondering what cufiNUFFT is using streams for. I searched from `streams` and couldn't find any places where this is used, so is this WIP?

**Comment by MelodyShih** [comment]
Hi Johannas, no, this is not WIP and the lines of codes can be removed. The streams were created in an experiment of accelerating computations when we have multiple data with same locations of NUpts.

**Comment by JBlaschke** [comment]
Right! Thanks for the info. I will pick up https://github.com/flatironinstitute/cufinufft/pull/99 again, and move the stream descriptor into a struct that also sores device and context.
