### ISSUE TITLE
finishing up the 1D functionality

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/cufinufft#123]
I just added a bunch of 1D tests to the make tasks.
But we need Python interface for 1D, and "1dmany" (vectorized) testers. This is not too hard.

We should then push the release to 1.2.1 and make a github release tag.

**Comment by janden** [comment]
Agreed. I would say that adding the 1D transform constitutes a minor version bump, so we'd be at 1.3 then.

**Comment by ahbarnett** [comment]
py has 1d interfaces I believe. We're going to worry about tests over in the merged finufft repo instead...
