### ISSUE TITLE
Compiler Optimization flags

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/cufinufft#13]
I noticed this when I was making the timing change:

```
CXXFLAGS= -DNEED_EXTERN_C  -fPIC -O3 -funroll-loops -march=native -g -std=c++11
```

IIRC -g will override previous optimization levels (the -03 on the left in this case).

Because NVCC has its own opt flags, I don't really think this affected CUDA performance, but in case it would (or another layer of your code),  I'll push a patch momentarily.

**Comment by ahbarnett** [comment]
I use -O3 -g all the time w/ GCC, based on understanding that while -On can make debugging harder, -g doesn't slow down optimized code. Eg:
https://stackoverflow.com/questions/24117063/is-a-program-compiled-with-g-gcc-flag-slower-than-the-same-program-compiled-wit

In particular, -g doesn't override the optim level.

So, is your comment specific to Intel or NVCC compilers?

**Comment by garrettwrong** [comment]
No, I was pretty sure the order mattered. I use as well...    I thought -g -03 has debug symbols at 03 level.  -03 -g would have -g -O0 (overrides).  Its possible that I am wrong and this is just something that was true 10-20 years ago... I'll look a little

**Comment by garrettwrong** [comment]
It appears you are correct :).  It was an intel compiler thing, I guess I just blindly ordered it that way everywhere so long I forgot why... i'll close. Learned something new.  Thanks!

```
-g Produce symbolic debug information in object file. The compiler does not support the generation of debugging information in assemblable files. If you specify the -g option, the resulting object  file  will contain debugging information, but the assemblable file will not. The -g option changes the default optimization from -O2 to -O0. It is often a good idea to add -traceback also, so the compiler generates extra information in the object file to provide source file traceback information.
```
