### ISSUE TITLE
make headers/macros/lib symbols safe. eg FLT currently clashes with a typename in boost::ublas. 

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/cufinufft#141]
We need to professionalize headers (make public-facing macro names all safe, ie CUFINUFFT_*), library symbols (namespacing away private methods), and header locations, as we are doing with FINUFFT in https://github.com/flatironinstitute/finufft/pull/217

A relevant comment from mortenwp:

Along the same lines: the FLT in finufft defines clashes with a typename in boost::ublas.  (and I suspect that the same issue would exists in cufinufft)
The preprocessor changes the FLT to either float or double,so  ublas suddenly has some of its tempates defined as
 _template &lang;typename double&rang;_ 
I think that suggests that FLT maybe should be safeguarded as FINUFFT_FLT?  For the time being I seem to be able to get around by using an undef FLT before including the ublas headers, so its not show stopper

_Originally posted by @mortenwp in https://github.com/flatironinstitute/cufinufft/issues/138#issuecomment-1127504513_

**Comment by mortenwp** [comment]
Along the same lines of cleanup: the header file cufinufft_eitherprec.h include header files from both the src and contrib directories, requiring that the source and contrib tree needs to be part of any development installation.

Also I can see that the README tells me library version is 1.2, but I can only see v1.0 tag.

rgds
-Morten

**Comment by blackwer** [comment]
This has been resolved in the finufft repo
