### ISSUE TITLE
Help with possible pts dependent bug

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/cufinufft#144]
Hi, I've been debugging an issue I initially found in ASPIRE running our test suite via cufinufft.  (We're trying to revisit our GPU efforts and get them running in CI continually...).

I was able to reduce it to a problem that only requires invoking two calls to cufinufft using one of our fourier point sets.  Using a different set of points (commented out below) does not seem to induce the behavior afaict.

I am currently trying to debug it, but thought it might be worth floating here as well while I do that... 

```
import numpy as np
import pycuda.autoinit
import pycuda.driver as cuda
import pycuda.gpuarray as gpuarray
from cufinufft import cufinufft

# ====== Initial Example Data Load

# Our Fourier Points
freq = np.load('freq.npy')

# # Dummy grid, seems to work
# freq = np.mgrid[-np.pi:np.pi:16j, -np.pi:np.pi:8j].astype(np.float32).reshape(2,-1)


# mod doesn't seem to matter, so commenting out
# print('min max freqs:', np.min(freq), np.max(freq), freq)
# pts = np.mod(freq + np.pi, 2 * np.pi, ) - np.pi 
# print('min max pts:',np.min(pts), np.max(pts), pts)
pts = freq

# Signal
signal = np.ones((1,128), dtype=np.complex64)


# Sizes
sz = (8, 8)
ntransforms = signal.shape[0]
res_shape = (ntransforms, *sz)


# ===== Make plans and arrays

# Plan details
eps = 1e-7

plan32 = cufinufft(1, sz, ntransforms, eps, 1, dtype=np.float32)
plan64 = cufinufft(1, sz, ntransforms, eps, 1, dtype=np.float64)


# Result Device Arrays
#_result_gpu32 = gpuarray.GPUArray(res_shape, dtype=np.complex64)
#_result_gpu64 = gpuarray.GPUArray(res_shape, dtype=np.complex128)
# Just in case... initialize
_result_gpu32 = gpuarray.to_gpu(np.zeros(res_shape, dtype=np.complex64))
_result_gpu64 = gpuarray.to_gpu(np.zeros(res_shape, dtype=np.complex128))


# HtoD
_pts_gpu32 = gpuarray.to_gpu(pts)
_pts_gpu64 = gpuarray.to_gpu(pts.astype(np.float64))

# Set the points
plan32.set_pts(*_pts_gpu32)
plan64.set_pts(*_pts_gpu64)


# ===== Execution

_signal_gpu32 = gpuarray.to_gpu(signal)
_signal_gpu64 = gpuarray.to_gpu(signal.astype(np.complex128))

#input("<enter>")

# the second execute will be junk
plan32.execute(_signal_gpu32, _result_gpu32)
plan64.execute(_signal_gpu64, _result_gpu64)


# DtoH
_result32 = _result_gpu32.get()
_result64 = _result_gpu64.get()


print(abs(_result32))
print(abs(_result64))   # will be junk....
```

I've attached a tarball with the freq array to this post.

Right now I'm going to be inspecting the points right before `exec` stage.  I'm considering if there is some state or variables that might be scoped incorrectly; I have not found any yet.

Let me know if you have any ideas. Thanks!

[issue_repro.tgz](https://github.com/flatironinstitute/cufinufft/files/9725928/issue_repro.tgz)

**Comment by ahbarnett** [comment]
The first thing to look for would be global state of cufft. We had an issue like this with FFTW in FINUFFT (not involving 32 vs 64 bit types, but just with different threads). Maybe @MelodyShih @janden @JBlaschke have ideas.

PS @blackwer has started to integrate cufinufft into finufft, first at the repo level, but we plan to integrate as much code as possible, for long-term maintainability. There will be many decisions there, so I hope we can ping you about them or have a meeting.

Good to see you the other day.  Best, Alex

**Comment by garrettwrong** [comment]
That makes sense. I did check that the plans have a distinct cufft plan but nothing further than that.  I'll inspect some more there.  Only failing for certain point sets is causing me some cognitive dissonance.

Yes that integration sounds great; big project.  Was a pleasure, thanks!

**Comment by garrettwrong** [comment]
I think I narrowed corruption down to something occurring temporally around Step 3 of the second 2d1 execute; after returning from `CUDECONVOLVE2D` I see the junk... Continuing ...

**Comment by garrettwrong** [comment]
Getting back into debugging this.  Seeing some strange values for `fw`, but haven't been able to track it down yet.  I am able to tickle this just in single precision (without mixing data types or having multiple cufinufft plans).

**Comment by blackwer** [comment]
Thanks Garrett! Let me know if there's anything I can do to help. So many
changes it's hard to track this stuff down, so that kind of debugging
should fall on me somewhat. I'd like to understand better anyway.

**Comment by garrettwrong** [comment]
There was an error in the points for my last tarball but the behavior is the same.  (I missed a line of values, but they would have been zeros...).  Uploaded a more correct one. Sorry about that.

[nopy_example.tgz](https://github.com/flatironinstitute/cufinufft/files/9820626/nopy_example.tgz)

**Comment by garrettwrong** [comment]
Easier to just stash work in a branch on my fork.  Hopefully I'm making less mistakes on now.  Probably I should have gone right to cuda earlier when I was fresher, but I was initially inclined to think it was a bug in ASPIRE.

https://github.com/flatironinstitute/cufinufft/compare/master...garrettwrong:cufinufft:bug_example

**Comment by ahbarnett** [comment]
Hi Garrett,
Can I close this issue or is there still a bug, IYHO ? :)  Best, Alex

**Comment by garrettwrong** [comment]
Hrmm. I don't believe the bug was ever addressed. I haven't tried to reproduce it with the recent (final) version.  I will try to reproduce it tomorrow and update the issue :).

**Comment by garrettwrong** [comment]
Hi again. I am still able to reproduce this issue's example using the `v1.3` code built on our machine.

`Linux caf.math.princeton.edu.private 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 6 10:04:24 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux`

`rh/devtoolset/8`

`Cuda compilation tools, release 11.7, V11.7.64 Build cuda_11.7.r11.7/compiler.31294372_0`

```
(base) ➜  cuf_13_bug_repro_144 git clone -b bug_example git@github.com:garrettwrong/cufinufft.git    
Cloning into 'cufinufft'...
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.114.3'
Offending key for IP in /u/gbwright/.ssh/known_hosts:11
Matching host key in /u/gbwright/.ssh/known_hosts:21
Are you sure you want to continue connecting (yes/no)? yes
remote: Enumerating objects: 4970, done.
remote: Counting objects: 100% (1284/1284), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 4970 (delta 1177), reused 1146 (delta 1136), pack-reused 3686
Receiving objects: 100% (4970/4970), 1.72 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3579/3579), done.
(base) ➜  cuf_13_bug_repro_144 cd cufinufft 
(base) ➜  cufinufft git:(bug_example) git remote add upstream git@github.com:flatironinstitute/cufinufft.git
(base) ➜  cufinufft git:(bug_example) git fetch upstream

# < snip>

From github.com:flatironinstitute/cufinufft
 * [new tag]         v1.3       -> v1.3
(base) ➜  cufinufft git:(bug_example) git rebase v1.3      
First, rewinding head to replay your work on top of it...
Applying: Add site for tigergpu at Princeton
Applying: Update README with Princeton sites
Applying: add debug example cases
Applying: Add PACM site
Applying: debug symbols seems to tickle much more often...
(base) ➜  cufinufft git:(bug_example) module load  cudatoolkit/11.7 rh/devtoolset/8
(base) ➜  cufinufft git:(bug_example) make all site=PACM -j

<snip>

(base) ➜  cufinufft git:(bug_example) bin/example_1_32 
[gpu ] one targ: rel err in c[64] is 9.3e+04
fk[0:8]: -16466.515625, -6339.429688, 2939.932373, -18116.044922, -37109.199219, -18116.048828, 2939.932617, -6339.421387, -5856.102539, -11939.065430, 
(base) ➜  cufinufft git:(bug_example) bin/example_1_64
[gpu ] one targ: rel err in c[64] is 1.71e+03
fk[0:8]: 14.591308, 19.666844, 23.890922, 21.967780, 20.733888, 21.967777, 23.890929, 19.666834, 19.666833, 22.993997, 
(base) ➜  cufinufft git:(bug_example)

**Comment by blackwer** [comment]
Hi @garrettwrong. Significant changes have been made across the board in the current version of this in the [finufft](https://github.com/flatironinstitute/finufft/) repo. I'll try reproducing it there instead and link in this issue from there if it's reproducible. If you'd rather do the lifting, let me know. I'll probably start working on it in 10 minutes or so :)

**Comment by garrettwrong** [comment]
Hi, using the `finufft` master code does seem to resolve the issue on our platform as well.

Not worried about the error. The issue was the junk results in floats (often times was yielding nans as well).  Right now we have to cast everything to doubles to run with `cufinufft`.  It will be nice to resolve that when `finufft` is release and we update things.

@ahbarnett , it seems this can be resolved as fixed upstream in `finufft`, thanks for following up. Closing.
