### ISSUE TITLE
Compatibility with Pytorch

### ISSUE THREAD

**Issue by pierre-weiss** [flatironinstitute/cufinufft#154]
This is a great implementation. One regret I have is its lack of "direct" compatibility with Pytorch. To make it compatible, I followed the tweak indicated by Alban Gossard here : https://github.com/albangossard/Bindings-NUFFT-pytorch

And replaced 
`if not c.dtype == fk.dtype == self.complex_dtype:
    raise TypeError("cufinufft execute expects {} dtype arguments "
                    "for this plan. Check plan and arguments.".format(
                        self.complex_dtype))
ier = self._exec_plan(c.ptr, fk.ptr, self.plan)`
by
`ier = self._exec_plan(c, fk, self.plan)`
in cufinufft.py

Unfortunately, this results in memory leaks. Any advice on how to use this excellent implementation with Pytorch arrays ?

**Comment by blackwer** [comment]
We've sense moved `cufinufft` into the main `finufft` codebase. There is currently a PR with a working pytorch interface here: https://github.com/flatironinstitute/finufft/pull/326
That implementation should avoid memory leaks properly when using the plan object. Hopefully this will be put into the next major release. If you'd like to try it in the meantime, you'll need to build it yourself or make the relevant hacks to the python code. The underlying cufinufft C API has changed, so the python code requires a bit of work to backport to the release version though.

**Comment by pierre-weiss** [comment]
Dear Robert,

Thanks a lot for your fast answer. Together with Alban Gossard, we just
modified the nufft_bindings
<https://github.com/albangossard/Bindings-NUFFT-pytorch> with a strategy
similar to what is proposed in your link... We think there should be no
problem anymore for us temporarily. It will be nice to see finufft handling
pytorch near natively.

Best !
Pierre




Le lun. 14 août 2023 à 19:40, Robert Blackwell ***@***.***> a
écrit :
