### ISSUE TITLE
Question regarding running tests

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/cufinufft#24]
I noticed the following testing a PR and I confirmed I am seeing same in master.  I think I am running the test incorrectly.  @MelodyShih , can you tell me what I am doing wrong and give me a better invocation?  (Method 2 and 4 error levels look strange to me).

```
(base) ➜  cufinufft.15 git:(master) ✗ bin/cufinufft3d1_test 1 100 100 100
[time  ] cufinufft plan:		 0.12 s
[time  ] cufinufft setNUpts:		 0.00217 s
[time  ] cufinufft exec:		 0.544 s
[time  ] cufinufft destroy:		 0.0204 s
[Method 1] 1000000 NU pts to #1000000 U pts in 0.567 s (	1.77e+06 NU pts/s)
[gpu   ] one mode: abs err in F[37,26,13] is 5.92e-05
[gpu   ] one mode: rel err in F[37,26,13] is 2e-08
(base) ➜  cufinufft.15 git:(master) ✗ bin/cufinufft3d1_test 2 100 100 100
[time  ] cufinufft plan:		 0.123 s
[time  ] cufinufft setNUpts:		 0.0019 s
error: not enough shared memory (92160)
error: cnufftspread3d_gpu_subprob
error: cuspread3d, method(2)
[time  ] cufinufft exec:		 0.000488 s
[time  ] cufinufft destroy:		 0.0194 s
[Method 2] 1000000 NU pts to #1000000 U pts in 0.0218 s (	4.6e+07 NU pts/s)
[gpu   ] one mode: abs err in F[37,26,13] is 743
[gpu   ] one mode: rel err in F[37,26,13] is inf
(base) ➜  cufinufft.15 git:(master) ✗ bin/cufinufft3d1_test 4 100 100 100
[time  ] cufinufft plan:		 0.122 s
CUDA error at src/3d/spread3d_wrapper.cu:791 code=700(cudaErrorIllegalAddress) "cudaMemcpy(&totalnumsubprob,&d_subprobstartpts[n], sizeof(int),cudaMemcpyDeviceToHost)" 
(base) ➜  cufinufft.15 git:(master) ✗ bin/cufinufft3d1_test 4 10 10 10   
[time  ] cufinufft plan:		 0.118 s
[time  ] cufinufft setNUpts:		 0.000386 s
[time  ] cufinufft exec:		 0.000811 s
[time  ] cufinufft destroy:		 7.16e-05 s
[Method 4] 1000 NU pts to #1000 U pts in 0.00127 s (	7.88e+05 NU pts/s)
[gpu   ] one mode: abs err in F[3,2,1] is 1.28e+06
[gpu   ] one mode: rel err in F[3,2,1] is 0.163
```

**Comment by garrettwrong** [comment]
Oops, pasted wrong call, but still same question..

```
(base) ➜  cufinufft.15 git:(master) ✗ bin/cufinufft3d1_test 2 10 10 10   
[time  ] cufinufft plan:		 0.12 s
[time  ] cufinufft setNUpts:		 0.000258 s
error: not enough shared memory (92160)
error: cnufftspread3d_gpu_subprob
error: cuspread3d, method(2)
[time  ] cufinufft exec:		 4.39e-05 s
[time  ] cufinufft destroy:		 6.86e-05 s
[Method 2] 1000 NU pts to #1000 U pts in 0.00037 s (	2.7e+06 NU pts/s)
[gpu   ] one mode: abs err in F[3,2,1] is 38.6
[gpu   ] one mode: rel err in F[3,2,1] is inf
```

**Comment by MelodyShih** [comment]
Are you running with double precision? I didn't run into this problem on my machine:
![image](https://user-images.githubusercontent.com/8497594/83204408-c3d51f00-a119-11ea-92f7-20e4147dfe89.png)
If you are using double precision, making the bin size smaller would work, e.g. setting gpu_binsizex = gpu_binsizey = 8. The idea is that the padded bin needs to fit into the shared memory so whenever one gets error "not enough shared memory", trying a smaller bin is the first thing I would try. But I think running with single precision is the way to go. 

Regarding failure of gpu_method=4, I can reproduce the error. I need to look further into the codes to see what went wrong. Hopefully, it can be fixed soon.

**Comment by garrettwrong** [comment]
Actually, that is a good point. I bet I was built with doubles there. Yes, we talked about the double precision, I just didn't think about it when I ran the test binaries this morning :). I will remember next time, thanks.  We can close this out from my perspective, but I will leave open so you can tag and close it with anything relating to the method 4 test.

Thanks!
