### ISSUE TITLE
Harmonize C interface with that of Finufft

### ISSUE THREAD

**Issue by janden** [flatironinstitute/cufinufft#38]
The current interface was modeled on an early version of the Finufft plan interface, which has changed in the meantime.

- [x] Options passed to `cufinufft_makeplan`. Currently, the user has to set these manually as part of `plan`. We should follow Finufft in allowing the user to provide the options to `cufinufft_makeplan`.
- [x] Plan is a pointer to a struct as opposed to a struct. This should simplify the ctypes interface, among other things.
- [x] Naming. Really only `cufinufft_setNUpts` that should become `cufinufft_setpts`.
- [x] Merge C++ and C interfaces. Currently, we have `cufinufft` and `cufinufftc`. Ideally, we'd only have one. I know there have been issues with this in the past, but if we pass the options to `makeplan` and make the plan a pointer, a lot of the C++ dependency can be stashed away from the API.

I'm sure there are more things, but these are the first that come to mind.

**Comment by garrettwrong** [comment]
I could use some details on two of these:

First, the signature of makeplan is nearly identical between gv2 and cu implementation in latest code, and #6, up to `nufft_opts`. (plan is already a pointer in both implementations and in the cu py bindings).

```
int FINUFFT_MAKEPLAN(int type, int dim, BIGINT* n_modes, int iflag, int n_transf, FLT tol, FINUFFT_PLAN* plan, nufft_opts* o);
...
int CUFINUFFT_MAKEPLAN(int type, int dim, int *n_modes, int iflag, int ntransf, FLT tol, int maxbatchsize, CUFINUFFT_PLAN *d_plan);
```

Second, clarification regarding "allowing user to provide the options"... Do you mean just to port this logic and related changes?

```
  if (opts==NULL)                        // use default opts                                                                                                                                
    FINUFFT_DEFAULT_OPTS(&(p->opts));
  else                                   // or read from what's passed in                                                                                                                   
    p->opts = *opts;    // keep a deep copy; changing *opts now has no effect                                                                                                               
```

instead of the C/C++ user calling default_opts?  I'll make that change on the assumption, so it is ready, but I'd like to ensure that is what you meant so we can knock this list out...

Thanks.

**Comment by garrettwrong** [comment]
I think these are all drafted (up to anything I am missing via clarification) in #39 .

**Comment by janden** [comment]
Thanks for taking a look at this.

> First, the signature of makeplan is nearly identical between gv2 and cu implementation in latest code, and #6, up to `nufft_opts`. (plan is already a pointer in both implementations and in the cu py bindings).

I'm looking at master, and it looks like `CUFINUFFT_PLAN` is a struct there, which means that the argument to `cufinufft_makeplan` is a pointer. In the Finufft interface, `FINUFFT_PLAN` is a pointer, so the argument in `finufft_makeplan` is a double pointer. In the first case, the user has to allocate the struct and pass a pointer to it in. In the second, you pass in a double pointer, `makeplan` allocates the struct and sets the pointer. This is the behavior that we'd want to have, in addition to redefining `CUFINUFFT_PLAN` to be a pointer to a struct.

> Second, clarification regarding "allowing user to provide the options"... Do you mean just to port this logic and related changes?

Yes. The idea is to not have the user mess around with internal fields in the plan struct, instead the opts are just provided once and for all to `makeplan`. As an added bonus, you get default opts by specifying NULL.

> I think these are all drafted (up to anything I am missing via clarification) in #39 .

Thanks. I'll take a look at this once it's undrafted.

**Comment by garrettwrong** [comment]
Okay, you want a double pointer; sure. For some reason the guru branch I was looking at this morning still has a single pointer in practice, maybe I was not up to date.  I'll try to resolve that tomorrow morning.

Yes the default_opts stuff is cleaner, good call.

Cool.

**Comment by janden** [comment]
Great. Yeah I just double-checked and it's a double pointer in Finufft (other functions have a single pointer since they're not allocating). Thank you!

**Comment by garrettwrong** [comment]
I pushed the changes for double pointer to the draft, including the removal of the struct definition from the python.  I am thinking to wait for Melody's review of #6 so that the PR #39  is naturally rebased before I review for undrafting. With that said, I don't think we're far away...
