### ISSUE TITLE
Release Tagging

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/cufinufft#44]
After #42 is in , I think we should tag a release candidate `v1.0-rc`.  I will base the container and wheels off of that commit and get them ready for staging. (initial tests seem good)

Once #43 completes, can push to Test PyPI index, at which time the wheels may be field tested with:
`pip install -i https://test.pypi.org/simple/ --no-deps cufinufft`

Following that, assuming no changes required, the `v1.0` tag can be created at the same commit, and the packages pushed to the live index.

This would give ASPIRE enough to tie to and test against. It would still allow for the software to be iterated on further before any formal announcement.  The very first release is always has a bit of the chicken-egg dance.

**Comment by garrettwrong** [comment]
@MelodyShih , does this sound okay to you? I'd like the make the release candidate tomorrow morning so everything is ready as soon as the PyPA approves the size limit increase.  Thanks

**Comment by garrettwrong** [comment]
`v1.0-rc` is tagged https://github.com/flatironinstitute/cufinufft/releases/tag/v1.0-rc.

The manylinux2010 with CUDA 10 container has been built at that commit, and I've built the packages (hopefully last time for v1.0 :) ). They are sitting in a folder waiting for upload...

Local testing and testing on TigerGPU went well.  A log of the TigerGPU tests of the staged package [can be found over at ASPIRE](https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/189#issuecomment-665755410). I'm happy enough with how that went to move forward.

**Comment by MelodyShih** [comment]
Hi @garrettwrong , sorry for missing the message yesterday. The tagging of release candidate sounds good to me.

**Comment by garrettwrong** [comment]
No worries. The testing seemed to go fine.  Unless there is an objection I'd like to push the v1.0 tag and packages to the live pypi index.  This would permit ASPIRE to pick it up as part of a `pip install` and move on with development over there.

Even if we add things, I don't expect the python API to change in a major way anytime soon.

**Comment by garrettwrong** [comment]
Cool, they're live. Thanks! Closing.
