### ISSUE TITLE
Vestigial Dependence on FFTW

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/cufinufft#45]
A user had a case where they were have conflicts integrating an FFTW install at a HPC with cufinufft.

FFTW dependence was brought over from FINUFFT in the process of trying to use their headers in contrib. To the best of my knowledge cufinufft uses cuFFT exclusively. Besides the vestigial lines from the parent repo, we don't use FFTW here.

So we need to decide which is more important. Travelling light (removing the unused dependence), or having the contrib files from another project be as similar/identical as possible. Since the files already required changing, I might suggest trimming the dependence.

I will push a PR shortly that removes it for consideration. Its a very small change.

**Comment by ahbarnett** [comment]
I agree - no need for FFTW.  All internal tests can use direct eval, and a separate repo could compare FINUFFT vs cuFINUFFT.

**Comment by JBlaschke** [comment]
This is only related in the sense that you've made me think of cuFFT vs a more general FFT backend: I assume that a HIP version is not in the pipeline?

**Comment by garrettwrong** [comment]
Not that I am aware of. It's not my project, but from what I gathered I think this project is trying to move closer to production, not integrate more academic research code at the systems level. It still has a ways to go, but has come along quickly.  Such decisions would change the trajectory of the project and its support requirements quite a bit.

**Comment by MelodyShih** [comment]
Hi Garrett, you're right about the dependency -- cufinufft only uses cuFFT and it doesn't depend on FFTW. There were codes that compare the results of finufft and cufinufft but are removed in #4. I should also remove those codes at the time. Thanks for cleaning this up.
