### ISSUE TITLE
set_pts memory leak

### ISSUE THREAD

**Issue by janden** [flatironinstitute/cufinufft#79]
I want to point out though that using `cufinufft` that way presupposes the user is carefully managing memory anyway, as  `CUFINUFFT_SETPTS`  always mallocs (which is assumed to be freed with the plan in `CUFINUFFT_DESTROY`) => so by setting new points without first destroying+creating a plan will cause a memory leak (this might be a good discussion in a different issue @MelodyShih @ahbarnett). 

_Originally posted by @JBlaschke in https://github.com/flatironinstitute/cufinufft/issues/71#issuecomment-767194388_

**Comment by MelodyShih** [comment]
Hi Joakim, I agree with the issue. I think adding a check to see if the arrays have already be allocated or not in function `ALLOCGPUMEM2,3D_NUPTS` before malloc them will fix it. I will create a pull request to fix it.

**Comment by janden** [comment]
Fixed by #80.
