### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by janden** [flatironinstitute/cufinufft#87]
Various things to address here:

- Add @JBlaschke as a contributor.
- Add Python usage example.
- Fix typo in C++ usage (we get default options but don't use them, maybe just get rid of this step).
- Minor typos & formatting.

I can take a look at this later. Just wanted to check if there's other things here that I can take care of while I'm at it.

**Comment by ahbarnett** [comment]
I did the first! I also did a PR on the spread/interp testers. I think I'll leave at that for now.
